/* DSA Revision Tracker — markdown generator (plan v2).
 *
 * Turns data/plan.json + data/progress.json into browsable files in the repo:
 *
 *   problems/<id>/README.md        link, difficulty, concepts, days, status, verification, statement (custom),
 *                                  notes, references, images, next revision
 *   problems/<id>/solution.<ext>   your code (written by the app, not generated here)
 *   concepts/<conceptId>.md        concept notes block + days, time, revisions, problems and their notes
 *   concepts/README.md             concept index with progress
 *   schedule.md                    every day (planned date, done, time) + upcoming revisions
 *
 * The block between <!-- notes:start --> and <!-- notes:end --> in a concept file is yours (edit it in the
 * app or on GitHub); regeneration keeps it and rewrites the rest.
 *
 * Problem notes are markdown stored in progress.json; relative links in them are relative to
 * problems/<id>/README.md and are rebased when embedded in a concept page.
 *
 * Shared by the browser (window.DSA_MD) and Node (scripts/build-docs.js). Needs lib/planlib.js.
 */
(function (root, factory) {
  var P = typeof module === "object" && module.exports ? require("./planlib.js") : root.DSA_PLAN;
  var api = factory(P);
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.DSA_MD = api;
})(typeof self !== "undefined" ? self : this, function (P) {
  "use strict";

  var LANGS = {
    cpp:    { ext: "cpp",  label: "C++",        fence: "cpp" },
    python: { ext: "py",   label: "Python",     fence: "python" },
    java:   { ext: "java", label: "Java",       fence: "java" },
    js:     { ext: "js",   label: "JavaScript", fence: "javascript" },
    ts:     { ext: "ts",   label: "TypeScript", fence: "typescript" },
    go:     { ext: "go",   label: "Go",         fence: "go" },
    rust:   { ext: "rs",   label: "Rust",       fence: "rust" },
    kotlin: { ext: "kt",   label: "Kotlin",     fence: "kotlin" },
    csharp: { ext: "cs",   label: "C#",         fence: "csharp" },
    c:      { ext: "c",    label: "C",          fence: "c" }
  };
  var DIFF = { E: "Easy", M: "Medium", H: "Hard" };
  var STATUS = { todo: "To do", solved: "✅ Solved", review: "🔁 Needs review" };
  var VERIFY = { verified: "✅ verified", builtin: "📚 curated", overridden: "☑ kept (override)", mismatch: "⚠ better fit elsewhere", unverified: "❔ unverified" };
  var HEADER = "<!-- Generated by DSA Revision Tracker. Edit via the app or data/*.json; manual edits here are overwritten. -->\n\n";
  var CONCEPT_HEADER = "<!-- Generated by DSA Revision Tracker. Only the text between notes:start and notes:end is yours to edit\n" +
    "     (here on GitHub or in the app); everything else is regenerated. -->\n\n";
  var NOTES_START = "<!-- notes:start -->";
  var NOTES_END = "<!-- notes:end -->";
  var CONCEPTS_INDEX = "concepts/README.md";
  var SCHEDULE = "schedule.md";

  function pad2(n) { return (n < 10 ? "0" : "") + n; }
  function cell(s) { return String(s == null ? "" : s).replace(/\|/g, "\\|").replace(/\n/g, " "); }

  // ---- paths ----
  function problemDir(id) { return "problems/" + id; }
  function problemReadmePath(id) { return problemDir(id) + "/README.md"; }
  function solutionPath(id, lang) { return problemDir(id) + "/solution." + (LANGS[lang] || LANGS.cpp).ext; }
  function problemImagePath(id, ext) { return problemDir(id) + "/images/" + Date.now() + "." + ext; }
  function conceptPath(cid) { return "concepts/" + cid + ".md"; }
  function conceptImagePath(cid, ext) { return "concepts/images/" + cid + "-" + Date.now() + "." + ext; }
  // v1 file name of a day's concept page (for migration)
  function legacyConceptPath(dayNumber, pattern) { return "concepts/day-" + pad2(dayNumber) + "-" + P.slugify(pattern) + ".md"; }

  // relative path from the directory of `fromFile` to `toPath` (both repo-relative)
  function rel(fromFile, toPath) {
    var from = fromFile.split("/"); from.pop();
    var to = toPath.split("/");
    var i = 0;
    while (i < from.length && i < to.length - 1 && from[i] === to[i]) i++;
    var up = [];
    for (var j = i; j < from.length; j++) up.push("..");
    return up.concat(to.slice(i)).join("/");
  }
  // repo path of `relPath` as written inside `fromFile`
  function resolve(fromFile, relPath) {
    var parts = fromFile.split("/"); parts.pop();
    relPath.split("/").forEach(function (seg) {
      if (seg === "..") parts.pop();
      else if (seg !== "." && seg !== "") parts.push(seg);
    });
    return parts.join("/");
  }
  function isRelative(url) { return !!url && !/^([a-z][a-z0-9+.-]*:|\/|#)/i.test(url); }
  // rewrite relative ](links) in markdown written for `fromFile` so they work from `toFile`
  function rebase(md, fromFile, toFile) {
    return String(md).replace(/\]\(([^)\s]+)/g, function (m, url) {
      return isRelative(url) ? "](" + rel(toFile, resolve(fromFile, url)) : m;
    });
  }

  // ---- time log ----
  // progress.days[id].sessions = [{ start, end }] as ISO strings with the local UTC offset; end null = running.
  function sessionMinutes(s, now) {
    if (!s || !s.start) return 0;
    var a = Date.parse(s.start), b = s.end ? Date.parse(s.end) : (now || Date.now());
    return b > a ? Math.round((b - a) / 60000) : 0;
  }
  function sessionsOf(dp) { return (dp && dp.sessions) || []; }
  function dayMinutes(dp, now) {
    return sessionsOf(dp).reduce(function (t, s) { return t + sessionMinutes(s, now); }, 0);
  }
  // calendar dates (YYYY-MM-DD, as written in the timestamps) covered by the sessions
  function datesWorked(dp) {
    var seen = {};
    sessionsOf(dp).forEach(function (s) {
      if (!s.start || (s.end && Date.parse(s.end) <= Date.parse(s.start))) return;
      var a = s.start.slice(0, 10), b = (s.end || s.start).slice(0, 10);
      for (var d = a, i = 0; d <= b && i < 400; d = P.addDays(d, 1), i++) seen[d] = true;
    });
    return Object.keys(seen).sort();
  }
  function fmtMinutes(m) {
    if (!m) return "0m";
    var h = Math.floor(m / 60), r = m % 60;
    return (h ? h + "h" : "") + (h && r ? " " : "") + (r ? r + "m" : "");
  }
  function wallClock(iso) { return iso ? iso.slice(0, 10) + " " + iso.slice(11, 16) : ""; }
  function sessionsTable(ss) {
    var out = "| # | Start | End | Duration |\n|---|---|---|---|\n";
    ss.slice().sort(function (a, b) { return Date.parse(a.start) - Date.parse(b.start); }).forEach(function (s, i) {
      out += "| " + (i + 1) + " | " + wallClock(s.start) + " | " + (s.end ? wallClock(s.end) : "⏱ running") + " | " +
        (!s.end ? "—" : Date.parse(s.end) <= Date.parse(s.start) ? "⚠ end before start" : fmtMinutes(sessionMinutes(s))) + " |\n";
    });
    return out;
  }

  // ---- revisions ----
  function revisionsFor(progress, type, id) {
    return Object.keys(progress.revisions || {}).map(function (k) { return progress.revisions[k]; })
      .filter(function (r) { return r.target && r.target.type === type && r.target.id === id; })
      .sort(function (a, b) { return (a.dueDate || "").localeCompare(b.dueDate || ""); });
  }
  function nextRevision(progress, type, id) {
    return revisionsFor(progress, type, id).filter(function (r) { return r.state === "suggested" || r.state === "accepted"; })[0] || null;
  }
  function revLabel(r) {
    if (!r) return "—";
    return r.dueDate + (r.time ? " " + r.time : "") + (r.state === "suggested" ? " (suggested)" : "");
  }
  function revHistoryMd(progress, type, id) {
    var done = revisionsFor(progress, type, id).filter(function (r) { return r.state === "done" || r.state === "skipped"; });
    var next = nextRevision(progress, type, id);
    if (!done.length && !next) return "";
    var out = "## Revisions\n\n**Next:** " + revLabel(next) + (next && next.reason ? " — " + next.reason : "") + "\n\n";
    if (done.length) {
      out += "| Due | Done | Outcome |\n|---|---|---|\n";
      done.forEach(function (r) {
        out += "| " + (r.dueDate || "") + " | " + (r.completedAt ? r.completedAt.slice(0, 10) : "") + " | " + (r.state === "skipped" ? "skipped" : (r.outcome || "")) + " |\n";
      });
      out += "\n";
    }
    return out;
  }

  // ---- concept notes block ----
  function extractNotes(md) {
    if (md == null) return null;
    var s = String(md).replace(/\r\n/g, "\n");
    var a = s.indexOf(NOTES_START), b = s.indexOf(NOTES_END);
    if (a < 0 || b < a) return null;
    return s.slice(a + NOTES_START.length, b).replace(/^\n+|\s+$/g, "");
  }
  // v1 progress.concepts[dayNum] = { notes, images } -> block text for concepts/<cid>.md
  function legacyNotes(cid, c) {
    if (!c) return "";
    var text = (c.notes || "").trim();
    var imgs = (c.images || []).map(function (p, i) {
      return "![note " + (i + 1) + "](" + (/^data:/.test(p) ? p : rel(conceptPath(cid), p)) + ")";
    }).join("\n\n");
    return [text, imgs].filter(Boolean).join("\n\n");
  }

  // ---- shared bits ----
  function imagesMd(fromFile, images) {
    return (images || []).filter(function (p) { return !/^data:/.test(p); }).map(function (p, i) {
      var r = rel(fromFile, p);
      return "[![note " + (i + 1) + "](" + r + ")](" + r + ")";
    }).join("\n\n");
  }
  function linksMd(links) { return (links || []).map(function (u) { return "- <" + u + ">"; }).join("\n"); }
  function solutionLink(fromFile, pp) {
    if (!pp || !pp.solution || !pp.solution.path) return "";
    var L = LANGS[pp.solution.lang] || { label: pp.solution.lang };
    return "[" + L.label + " solution](" + rel(fromFile, pp.solution.path) + ")";
  }
  function problemLink(p) {
    var url = P.problemUrl(p);
    return url ? "[" + cell(p.title) + "](" + url + ")" : cell(p.title);
  }
  function verifyLabel(p) {
    var v = p.verification || {};
    var s = VERIFY[v.status] || VERIFY.unverified;
    if (v.confidence != null && v.status === "verified") s += " " + Math.round(v.confidence * 100) + "%";
    return s;
  }
  function dayLabel(plan, d) { return "Day " + P.dayNumber(plan, d.id) + " — " + d.title; }
  function pct(a, b) { return b ? Math.round(100 * a / b) : 0; }
  function bar(a, b) {
    var n = b ? Math.round(10 * a / b) : 0;
    return "`" + "█".repeat(n) + "░".repeat(10 - n) + "` " + pct(a, b) + "%";
  }

  // ---- problem README ----
  function problemReadme(plan, progress, pid) {
    var p = plan.problems[pid];
    var pp = progress.problems[pid] || {};
    var file = problemReadmePath(pid);
    var out = HEADER + "# " + p.title + "\n\n| | |\n|---|---|\n";
    if (p.kind === "leetcode") {
      out += "| **LeetCode** | [" + p.slug + "](" + P.problemUrl(p) + ") · [worked solutions](" + P.problemUrl(p) + "solutions/) |\n";
    } else {
      out += "| **Type** | Custom problem" + (p.url ? " · [link](" + p.url + ")" : "") + " |\n";
    }
    out += "| **Difficulty** | " + (DIFF[p.diff] || p.diff) + " |\n";
    if (p.conceptIds.length) {
      out += "| **Concept" + (p.conceptIds.length > 1 ? "s" : "") + "** | " + p.conceptIds.filter(function (c) { return plan.concepts[c]; })
        .map(function (c) { return "[" + cell(plan.concepts[c].name) + "](" + rel(file, conceptPath(c)) + ")"; }).join(" · ") + " |\n";
    }
    var days = P.problemDays(plan, pid);
    if (days.length) out += "| **Scheduled** | " + days.map(function (d) { return cell(dayLabel(plan, d)); }).join(" · ") + " |\n";
    out += "| **Status** | " + (STATUS[pp.status] || STATUS.todo) + " |\n";
    if (pp.revisedAt) out += "| **Last revised** | " + pp.revisedAt.slice(0, 10) + " |\n";
    var next = nextRevision(progress, "problem", pid);
    if (next) out += "| **Next revision** | " + revLabel(next) + " |\n";
    var sol = solutionLink(file, pp);
    if (sol) out += "| **Solution** | " + sol + " |\n";
    out += "| **Pattern check** | " + verifyLabel(p) + " |\n\n";
    if (p.verification && p.verification.reason) out += "> " + p.verification.reason.replace(/\n/g, "\n> ") + "\n\n";

    if (p.kind === "custom" && p.statement && p.statement.trim()) out += "## Problem\n\n" + p.statement.trim() + "\n\n";
    if (pp.notes && pp.notes.trim()) out += "## Notes\n\n" + pp.notes.trim() + "\n\n";
    if (pp.links && pp.links.length) out += "## References\n\n" + linksMd(pp.links) + "\n\n";
    var imgs = imagesMd(file, pp.images);
    if (imgs) out += "## Handwritten notes\n\n" + imgs + "\n\n";
    out += revHistoryMd(progress, "problem", pid);
    return out;
  }

  // ---- concept page ----
  // `notes` = block text from the existing file (null -> empty block)
  function conceptMd(plan, progress, cid, notes) {
    var c = plan.concepts[cid];
    var file = conceptPath(cid);
    var days = P.conceptDays(plan, cid);
    var probs = P.conceptProblems(plan, cid);
    var so = P.solvedOf(progress, probs.map(function (p) { return p.id; }));
    var out = CONCEPT_HEADER + "# " + c.name + "\n\n";
    if (c.summary) out += "> " + c.summary + "\n\n";
    out += "**Progress:** " + bar(so.solved, so.total) + " (" + so.solved + "/" + so.total + " solved)";
    var mins = days.reduce(function (t, d) { return t + dayMinutes(progress.days[d.id]); }, 0);
    if (mins) out += " · **Time:** " + fmtMinutes(mins);
    out += "\n\n";
    if (c.triggers && c.triggers.length) out += "**Recognise it when:** " + c.triggers.join(" · ") + "\n\n";
    if (c.leetcodeTags && c.leetcodeTags.length) out += "**LeetCode tags:** " + c.leetcodeTags.join(", ") + "\n\n";

    if (days.length) {
      out += "## Schedule\n\n| Day | Planned | Done | Time | Dates worked |\n|---|---|---|---|---|\n";
      days.forEach(function (d) {
        var dp = progress.days[d.id] || {};
        out += "| " + cell(dayLabel(plan, d)) + " | " + (P.plannedDate(plan, d) || "") + " | " + (dp.done ? "✅" : "") + " | " +
          (dayMinutes(dp) ? fmtMinutes(dayMinutes(dp)) : "") + " | " + datesWorked(dp).join(", ") + " |\n";
      });
      out += "\n";
      var all = [];
      days.forEach(function (d) { all = all.concat(sessionsOf(progress.days[d.id])); });
      if (all.length) out += "### Time log\n\n" + sessionsTable(all) + "\n";
    }

    out += revHistoryMd(progress, "concept", cid);
    out += "## Concept notes\n\n" + NOTES_START + "\n" + (notes ? notes + "\n" : "") + NOTES_END + "\n\n";

    if (probs.length) {
      out += "## Problems\n\n| # | Problem | Diff | Status | Pattern check | Solution | Page |\n|---|---|---|---|---|---|---|\n";
      probs.forEach(function (p, i) {
        var pp = progress.problems[p.id] || {};
        out += "| " + (i + 1) + " | " + problemLink(p) + (p.kind === "custom" ? " _(custom)_" : "") + " | " + p.diff + " | " +
          (STATUS[pp.status] || STATUS.todo) + " | " + verifyLabel(p) + " | " + (solutionLink(file, pp) || "—") + " | [page](" +
          rel(file, problemReadmePath(p.id)) + ") |\n";
      });
      out += "\n";
      probs.forEach(function (p) {
        var pp = progress.problems[p.id] || {};
        var imgs = imagesMd(file, pp.images);
        var hasNotes = pp.notes && pp.notes.trim();
        if (!hasNotes && !imgs && !(pp.links && pp.links.length) && !(pp.solution && pp.solution.path)) return;
        out += "### " + p.title + "\n\n" + (P.problemUrl(p) ? "[Problem](" + P.problemUrl(p) + ") · " : "") +
          "[page](" + rel(file, problemReadmePath(p.id)) + ")";
        var sol = solutionLink(file, pp);
        if (sol) out += " · " + sol;
        out += "\n\n";
        if (hasNotes) out += rebase(pp.notes.trim(), problemReadmePath(p.id), file) + "\n\n";
        if (pp.links && pp.links.length) out += linksMd(pp.links) + "\n\n";
        if (imgs) out += imgs + "\n\n";
      });
    }
    return out;
  }

  // ---- concepts index ----
  function conceptsIndex(plan, progress) {
    var file = CONCEPTS_INDEX;
    var st = P.stats(plan, progress, dayMinutes);
    var out = HEADER + "# Concepts\n\n";
    out += "**Problems:** " + bar(st.solved, st.problems) + " (" + st.solved + "/" + st.problems + ") · **Days:** " + st.daysDone + "/" + st.days +
      " · **Logged:** " + fmtMinutes(st.minutes) + " · [Schedule](../" + SCHEDULE + ")\n\n";
    out += "| Concept | Days | Solved | Pattern-checked | Time | Next revision |\n|---|---|---|---|---|---|\n";
    P.conceptsOrdered(plan).forEach(function (c) {
      var days = P.conceptDays(plan, c.id), probs = P.conceptProblems(plan, c.id);
      var so = P.solvedOf(progress, probs.map(function (p) { return p.id; }));
      var checked = probs.filter(function (p) { var s = (p.verification || {}).status; return s === "verified" || s === "builtin" || s === "overridden"; }).length;
      var mins = days.reduce(function (t, d) { return t + dayMinutes(progress.days[d.id]); }, 0);
      out += "| [" + cell(c.name) + "](" + rel(file, conceptPath(c.id)) + ") | " +
        days.map(function (d) { return P.dayNumber(plan, d.id); }).join(", ") + " | " +
        (so.total ? so.solved + "/" + so.total : "—") + " | " + (probs.length ? checked + "/" + probs.length : "—") + " | " +
        (mins ? fmtMinutes(mins) : "") + " | " + (nextRevision(progress, "concept", c.id) ? revLabel(nextRevision(progress, "concept", c.id)) : "") + " |\n";
    });
    return out + "\n";
  }

  // ---- schedule ----
  function scheduleMd(plan, progress) {
    var file = SCHEDULE;
    var st = P.stats(plan, progress, dayMinutes);
    var out = HEADER + "# Schedule\n\n";
    out += "**Days:** " + bar(st.daysDone, st.days) + " (" + st.daysDone + "/" + st.days + ") · **Problems:** " + st.solved + "/" + st.problems +
      " · **Logged:** " + fmtMinutes(st.minutes) + (plan.meta.startDate ? " · **Start:** " + plan.meta.startDate : "") + "\n\n";
    var lastPhase = null;
    plan.days.forEach(function (d) {
      if (d.phaseId !== lastPhase) {
        lastPhase = d.phaseId;
        var ph = P.phaseById(plan, d.phaseId);
        out += "\n## " + cell(ph ? ph.title : "Unphased") + "\n\n| Day | Title | Kind | Planned | Concepts | Solved | Time | Done |\n|---|---|---|---|---|---|---|---|\n";
      }
      var dp = progress.days[d.id] || {};
      var so = P.solvedOf(progress, d.problemIds.filter(function (pid) { return plan.problems[pid]; }));
      out += "| " + P.dayNumber(plan, d.id) + " | " + cell(d.title) + " | " + (P.KINDS[d.kind] || d.kind) + " | " + (P.plannedDate(plan, d) || "") + " | " +
        d.conceptIds.filter(function (c) { return plan.concepts[c]; }).map(function (c) { return "[" + cell(plan.concepts[c].name) + "](" + rel(file, conceptPath(c)) + ")"; }).join(", ") + " | " +
        (so.total ? so.solved + "/" + so.total : "—") + " | " + (dayMinutes(dp) ? fmtMinutes(dayMinutes(dp)) : "") + " | " + (dp.done ? "✅" : "") + " |\n";
    });
    var open = Object.keys(progress.revisions || {}).map(function (k) { return progress.revisions[k]; })
      .filter(function (r) { return r.state === "suggested" || r.state === "accepted"; })
      .sort(function (a, b) { return (a.dueDate || "").localeCompare(b.dueDate || ""); });
    if (open.length) {
      out += "\n## Upcoming revisions\n\n| Due | What | State |\n|---|---|---|\n";
      open.forEach(function (r) {
        var t = r.target, name, path;
        if (t.type === "concept" && plan.concepts[t.id]) { name = plan.concepts[t.id].name; path = conceptPath(t.id); }
        else if (t.type === "problem" && plan.problems[t.id]) { name = plan.problems[t.id].title; path = problemReadmePath(t.id); }
        else return;
        out += "| " + r.dueDate + (r.time ? " " + r.time : "") + " | " + (t.type === "concept" ? "Concept: " : "Problem: ") +
          "[" + cell(name) + "](" + rel(file, path) + ") | " + r.state + " |\n";
      });
    }
    return out + "\n";
  }

  // All generated files: [{ path, content }]. notesByConcept[cid] = existing block text.
  function allDocs(plan, progress, notesByConcept) {
    notesByConcept = notesByConcept || {};
    var files = [
      { path: CONCEPTS_INDEX, content: conceptsIndex(plan, progress) },
      { path: SCHEDULE, content: scheduleMd(plan, progress) }
    ];
    Object.keys(plan.concepts).forEach(function (cid) {
      files.push({ path: conceptPath(cid), content: conceptMd(plan, progress, cid, notesByConcept[cid]) });
    });
    Object.keys(plan.problems).forEach(function (pid) {
      files.push({ path: problemReadmePath(pid), content: problemReadme(plan, progress, pid) });
    });
    return files;
  }

  return {
    LANGS: LANGS, VERIFY: VERIFY, CONCEPTS_INDEX: CONCEPTS_INDEX, SCHEDULE: SCHEDULE,
    rel: rel, resolve: resolve, isRelative: isRelative, rebase: rebase,
    problemDir: problemDir, problemReadmePath: problemReadmePath, solutionPath: solutionPath, problemImagePath: problemImagePath,
    conceptPath: conceptPath, conceptImagePath: conceptImagePath, legacyConceptPath: legacyConceptPath,
    extractNotes: extractNotes, legacyNotes: legacyNotes,
    sessionMinutes: sessionMinutes, dayMinutes: dayMinutes, datesWorked: datesWorked, fmtMinutes: fmtMinutes,
    nextRevision: nextRevision, revisionsFor: revisionsFor,
    problemReadme: problemReadme, conceptMd: conceptMd, conceptsIndex: conceptsIndex, scheduleMd: scheduleMd, allDocs: allDocs
  };
});
